name: Tests Full

on:
  schedule:
    - cron:  '4 5 * * 2'

jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MacOS dependencies
        run: |
            brew install libomp
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install dependencies
        run: |
            pip install -r prereq.txt
            pip install .
            pip install .[testing]
      - name: Test with pytest
        run: pytest -vvvsx
